name: learn-github-actions
run-name: ${{github.actor}} is deploying cte-app
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  deploy-cte-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i

      - name: Build static file
        run: npm run build

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949024534101:role/github-oidc
          role-session-name: GitHubOIDCForAWSSession
          aws-region: us-east-1
          
      - name: Copy to S3
        run: aws s3 sync ./build s3://collaborative-text-editor-app