name: learn-github-actions
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  aws-sync-bucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Copy to S3
        run: aws s3 sync ./ s3://collaborative-text-editor-app